name: bioconnect
description: A health monitoring app for families

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Notifications & Storage
  shared_preferences: ^2.2.3

  # Supabase dependencies
  supabase_flutter: ^2.5.6

  # Chart library for statistics
  fl_chart: ^0.68.0

  # Network & Crypto
  http: ^1.1.0
  crypto: ^3.0.3

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  # assets:
  #   - images/

  # Add custom fonts here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
