name: your_app_name
description: Your app description

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^2.3.2

  # HTTP & State Management
  http: ^1.4.0
  provider: ^6.1.5
  equatable: ^2.0.7

  # Phone Number & Device Paths
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.5

  # Authentication & Storage
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Notifications & Local Features (Downgraded to avoid NDK conflict)
  flutter_local_notifications: ^19.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login_background.png
    - assets/google.png
    - assets/facebook.png
    - assets/x.png
