// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRPlqU1V6t3i5igBRwqzHQgkUjkuV1244',
    appId: '1:528719596592:web:18a25233ea2ea058f831f5',
    messagingSenderId: '528719596592',
    projectId: 'bioconnect-9b916',
    authDomain: 'bioconnect-9b916.firebaseapp.com',
    storageBucket: 'bioconnect-9b916.firebasestorage.app',
    measurementId: 'G-T3NW8LF763',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLziGnDh37gdiK3PMN7YjttZSDxpHDqAQ',
    appId: '1:528719596592:android:ad34b3ce71c0fde4f831f5',
    messagingSenderId: '528719596592',
    projectId: 'bioconnect-9b916',
    storageBucket: 'bioconnect-9b916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoVMth947j4amVNkyPKtIxF8Gztbk3ihk',
    appId: '1:528719596592:ios:1e6a0b09b5210497f831f5',
    messagingSenderId: '528719596592',
    projectId: 'bioconnect-9b916',
    storageBucket: 'bioconnect-9b916.firebasestorage.app',
    iosClientId: '528719596592-65e1lqe6rmflu060n2aooomaqdng6shk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoVMth947j4amVNkyPKtIxF8Gztbk3ihk',
    appId: '1:528719596592:ios:1e6a0b09b5210497f831f5',
    messagingSenderId: '528719596592',
    projectId: 'bioconnect-9b916',
    storageBucket: 'bioconnect-9b916.firebasestorage.app',
    iosClientId: '528719596592-65e1lqe6rmflu060n2aooomaqdng6shk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRPlqU1V6t3i5igBRwqzHQgkUjkuV1244',
    appId: '1:528719596592:web:fd565eda7a374adbf831f5',
    messagingSenderId: '528719596592',
    projectId: 'bioconnect-9b916',
    authDomain: 'bioconnect-9b916.firebaseapp.com',
    storageBucket: 'bioconnect-9b916.firebasestorage.app',
    measurementId: 'G-70W560TF8N',
  );
}
